server:
  port: 8080

spring:
  application:
    name: ead-api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: authuser-service
            uri: lb://EAD-AUTHUSER-SERVICE
            predicates:
              - Path=/ead-authser/**
          - id: curse-service
            uri: lb://EAD-COURSE-SERVICE
            predicates:
              - Path=/ead-curse/**  -

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost