server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'

spring:
  application:
    name: ead-authuser-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non-contextual-creation: true
  output:
    ansi:
      enabled: always
  rabbitmq:
    addresses: amqps://jgjxjoub:fYM-Tt8KAGwjBcgZuWGE51PoD2fz9iew@chimpanzee.rmq.cloudamqp.com/jgjxjoub


logging:
  level:
    com.ead: TRACE


ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'
  broker:
    exchange:
      userEvent: ead.userevent

  auth:
    jwtSecret: aW?hd1b2WeSLmr=R3!ppokpK/pX53eJT82?WpsHTtFU?N9=xySyo9Py?XOJH8hDa
    jwtEpirationMs: 14400000


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
